# Activity

- Now it's your turn!
- You can find a data set titled "clinician.csv" in the supplemental material linked [here](https://github.com/jimmyrigby94/Data-Management-in-R/tree/master/suppl).
- A .txt file (clinician_description.txt) is also included describing the data and structure.
- Your goal is to clean the data and then summarise the data in a meaningful way. 
- Instructions may, at times, be intentionally ambiguous.
- This is intended to facilitate critical thinking when applying the principles learned. 

<div class = activity>
<div class = activitytitle>
Instructions</div>
**Data Cleaning**

1. Create a dataframe with only the current patients.

2. Remove irrelevant columns. 

3. Assign meaningful names to all columns.

4. Remove observatons that have NO data for Beck Depression Inventory and Subjective Well-Being scales.

5. Create scale scores using arithmetic operators.

6. Create scale scores using a method that employs a function to generate the mean.

7. Create a varaible that stores the depression CDF for each participant. 


**Group-Level Feature Extraction**

1. Create a variable that stores therapist-level depression scores for each participant

2. Create a variable that stores therapist-level attrition rate. 

**Summary Statistics**

1. Create a separate data frame that summarises the sample's central tendency (i.e., mean, median, and mode) and spread (i.e., variance, standard deviation, and mad). 

2. Create an identical table, except calculate these summary statistics across therapists.

3. Which therapist has the highest attrition rate?

4. Which therapist has the highest recovery rate?

5. Is there an association between the Recrutiment Medium and recovery rate?

**Follow-up Quesitons**

1. What was the difference between scale scores generated by arithmetic operators and functions?

2. Did the information stored within group-level features differ than what was generated in the grouped summary statistics?

3. When would it be useful to store group-level data as a summary table versus a variable in the original data frame?
</div>



